### ISSUE TITLE
Rework the servers page

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1503]
A page with a table of all known server implementations.

The table contains:
* Project Name
* Project Maintainer
* Maturity
* Language
* Licence
* Repo (optional)
* Room (optional)
* Two sentences description

Eventually, the last release date and a set of features the server supports will be added, but this can be done post-launch.

Data of the servers:

```toml
[[servers]]
name = "Synapse"
description = "Matrix.org homeserver"
author = "Matrix.org team"
maturity = "Released"
language = "Python"
license = "Apache-2.0"
repo = "https://github.com/matrix-org/synapse/"
room = "#synapse:matrix.org"

[[servers]]
name = "Dendrite"
description = "Dendrite is a second-generation Matrix homeserver written in Go!"
author = "Matrix.org team"
maturity = "Beta"
language = "Go"
license = "Apache-2.0"
repo = "https://github.com/matrix-org/dendrite"
room = "#dendrite:matrix.org"

[[servers]]
name = "Conduit"
description = "Conduit is a simple, fast and reliable chat server written in Rust"
author = "Timo Kösters"
maturity = "Beta"
language = "Rust"
license = "Apache-2.0"
repo = "https://gitlab.com/famedly/conduit"
room = "#conduit:matrix.org"

[[servers]]
name = "Construct"
description = "Construct is a C++ Matrix Homeserver"
author = "Jason Volk"
maturity = "Beta"
language = "C++"
license = "BSD"
repo = "https://github.com/matrix-construct/construct"

[[servers]]
name = "Ligase"
description = "Ligase is a Cloud-native Matrix home server written in Golang."
author = "Finogeeks team"
maturity = "Beta"
language = "Go"
license = "AGPLv3"
repo = "https://github.com/finogeeks/Ligase"

[[servers]]
name = "bullettime"
description = "An experimental golang Matrix homeserver"
maintainer = "Patrik Oldsberg"
maturity = "Not actively maintained"
language = "Go"
license = "Apache-2.0"
repo = "https://github.com/matrix-org/bullettime"

[[servers]]
name = "Dendron"
description = "Discontinued in favour of Dendrite (\"Dendron, done right\")"
author = "Matrix.org team"
maturity = "Not actively maintained"
language = "Go"
license = "Apache-2.0"
repo = "https://github.com/matrix-org/dendron"

[[servers]]
name = "jSynapse"
author = "Swarmcom"
language = "Java"
maturity = "Not actively maintained"
license = "Apache-2.0"

[[servers]]
name = "Maelstrom"
description = "A high-performance Matrix Home-Server written in Rust designed to be scalable, light on resources, and have a pluggable storage engine."
author = "Chris Bruce"
maturity = "Not actively maintained"
language = "Rust"
license = "Apache-2.0 OR MIT"
repo = "https://github.com/maelstrom-rs/maelstrom"
room = "#maelstrom-server:matrix.org"

[[servers]]
name = "Matrex"
description = "A WIP toy Matrix server implementation in Elixir."
author = "Ryan Johnson"
maturity = "Not actively maintained"
language = "Elixir"
license = "MIT"
repo = "https://github.com/bismark/matrex"

[[servers]]
name = "mxhsd"
description = "mxhsd is Matrix Homeserver aimed towards entities who want to have in-depth control of their servers"
author = "Max Dor"
maturity = "Not actively maintained"
language = "Java"
license = "AGPL-3.0-or-later"
repo = "https://github.com/kamax-io/mxhsd"

[[servers]]
name = "Pallium"
author = "KoFish"
language = "Go"
maturity = "Not actively maintained"
license = "Apache-2.0"
repo = "https://github.com/KoFish/pallium"

[[servers]]
name = "Transform"
description = "Transform is a matrix homeserver built using Typescript and Redis."
author = "bettiah"
maturity = "Not actively maintained"
language = "TypeScript"
license = "Apache-2.0"
repo = "https://github.com/bettiah/transform"
```
