### ISSUE TITLE
Rework the Hosting page

### ISSUE THREAD

**Issue by thibaultamartin** [matrix-org/matrix.org#1541]
## Goal of the page

- Not very relevant for everyday people, unless we start adding services like Beeper and Element One/Home?
- Convince community managers they can painlessly get their own Matrix instance, with their branding (i.e. their domain for Matrix IDs)
- Convince community managers that Matrix hosting services are reliable and won't go away anytime soon
- Not very relevant for developers?
- Convince entrepreneurs that people are looking for Matrix hosted services

## Content of the page

A page with two main sections:
On top: an introduction of hosting services and providers are:

```markdown
## What is Matrix hosting

Matrix could be described as what happens when email, instant messaging and
encryption meet. To be able to use Matrix, you need a Matrix account which is
provided by... a provider! The matrix accounts identifiers look like
`@username:example.com`. People on different providers can talk to one another,
in the same way you can send emails to someone using another email provider.

Matrix.org is the largest, free provider of Matrix accounts. Many people have an
identifier like `@username:matrix.org`. This also means that the Matrix.org
servers are crowded. Using your own provider **as an individual** can not only
make your Matrix experience snappier, but also give you access to a set of
pre-configured [bridges]() to talk to friends on other networks such as Signal
or WhatsApp.

**Organisations and community managers** will be interested in providers for two
main reasons: they can proudly display their identity with their own domain
in username and rooms identifiers, and their administrators remain in control
of the data of their organisation.

The following providers have been brought to the attention of the Matrix.org
Foundation. Please note that the Matrix.org Foundation doesn't endorse them,
nor provides any warranties for using them.
```

After that:
A grid view of all Matrix hosting services (maybe a card for each service, a little like the featured clients?), with their logo, name, for how long they have been operating, and the services they can host, and a link to the provider.
Very similar to https://matrix.org/hosting/

For now we're keeping the services they can host a freeform (markdown), but we may standardise that later.

Data is:

```toml
# Add me: Beeper?

[[providers]]
name = "Element Matrix Services"
website = "https://ems.element.io"
operating_since = "2018"
description = """
- Hosted Homeservers
- [Hosted Integrations including Slack, IRC, Github bridging](https://element.io/element-matrix-store)

Brought to you by the creators of Matrix, who have been running the biggest homeserver in the network since 2014. Every homeserver comes with a custom instance of Element.
"""

[[providers]]
name = "Ungleich.ch"
website = "https://matrix.zerocarbon.shop"
operating_since = "TBC"
description = """
- Hosted Homeservers

Service provided by [ungleich.ch](https://ungleich.ch/) in their own datacenter in Linthal, Switzerland. They use an old building, second-hand servers, passive cooling and are directly plugged into an on-site hydroelectric power plant!
"""

[[providers]]
name = "etke.cc"
website = "https://etke.cc"
operating_since = "TBC"
description = """
- Setup of hosted Homeserver on any hosting by your choice
- Setup of hosted integrations (full list available on website)
- Setup of additional services (wireguard, languagetool, miniflux, etc.)
- Ongoing maintenance of host & Matrix components
- Email services for your domain
 
That service will create your Matrix Homeserver on your domain and server (doesn't matter if it's cloud provider or on an old laptop in the corner of your room), (optional) maintains it (server's system updates, cleanup, security adjustments, tuning, etc.; Matrix Homeserver updates & maintenance) and (optional) provide full-featured email service for your domain.

[Matrix Space](https://matrix.to/#/#service:etke.cc)  | [Announcements on Matrix](https://matrix.to/#/#announcements:etke.cc)
"""

[[providers]]
name = "Ossrox"
website = "https://ossrox.org"
operating_since = "TBC"
description = """
- Hosted Homeservers
 
Ossrox is a company from Germany dedicated to hosting open-source services. Not only has the company name been derived from the motto "Open-Source Software Rocks", but also their corporate culture. The three most important principles of the company are security, privacy and sustainability - thanks to open-source software. In addition to Matrix, Ossrox also provides many other solutions e.g. in the messaging, groupware and web meeting segments.
"""
```
