### ISSUE TITLE
Not able to create recovery keys  for OIDC users, as Synpase tries auth against local LDAP instead

### ISSUE THREAD

**Issue by linuxmail** [matrix-org/matrix.org#1807]
Hello,

our Synpase 1.79.0+buster1 on Debian Buster has local LDAP users and users via OIDC:

```
....
password_providers:
 - module: "ldap_auth_provider.LdapAuthProvider"
   config:
     enabled: true
     uri: "ldap://192.1.2.3
...
oidc_providers:
  - idp_id: microsoft
    idp_name: Microsoft
...
```
If the user which used OIDC login try to create recovery keys (Element 1.11.31), than it asks for account password. The log says, it tries to connect to the LDAP server, like:

```
2023-05-23 14:17:54,332 - ldap_auth_provider - 637 - INFO - POST-22422607- LDAP search returned no results for '[('sAMAccountName', 'denny.fuchs')]'
````

which can't work.

Any suggestions ?
