### ISSUE TITLE
Use sticky headers for tables

### ISSUE THREAD

**Issue by afranke** [matrix-org/matrix.org#227]
Pages such as the client matrix one have tables that can be quite long and sticky headers improve readability vastly. Something along the lines of
```css
thead {
  position: sticky;
  top: 52px;
}
```
would work. Problem is that value of 52px comes from the 10px margin + 42px height of `#main-header` that I can see here but I don’t how to make that more reliable.
