### ISSUE TITLE
New bridge: matrix-appservice-revolt

### ISSUE THREAD

**Issue by austinhuang0131** [matrix-org/matrix.org#2389]
```toml
[[bridges]]
name = "matrix-appservice-revolt"
maintainer = "Austin Huang"
summary = "Bridges Revolt and Matrix via the Application Service API."
maturity = "Alpha"
language = "TypeScript"
license = "AGPL-3.0-or-later"
docs = "https://codeberg.org/austinhuang/matrix-appservice-revolt/wiki"
repo = "https://codeberg.org/austinhuang/matrix-appservice-revolt"
room = "#matrix-appservice-revolt:bus-hit.me"
featured = false # i don't know how it works
privilege.platform = "Admin"
privilege.matrix = "Homeserver Admin"
[bridges.supports]
dm = false
channels = true
formatted_text = true
message_media = true
replies = true
mentions = true
threads = false # Revolt doesn't have Threads
redactions = true
editing = true
reactions = false
presence = false
typing_notifications = false
```

Regarding the icon: The R is available [here](https://github.com/revoltchat/revite/blob/2722d0a8544a81f1c44e6afbce45e7c10dd7a095/src/pages/settings/assets/revolt_r.svg?plain=1). The dark background is missing, but should be fairly easy to add (plain `#111822` with round corners).
